# Generated by Django 3.0.6 on 2020-12-13 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'stock',
                'verbose_name_plural': 'stocks',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='StockProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.ProductColor')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
                ('stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.Stock')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.ProductType')),
            ],
            options={
                'verbose_name': 'stockproduct',
                'verbose_name_plural': 'stockproducts',
                'ordering': ('product',),
            },
        ),
    ]
