# Generated by Django 3.0.6 on 2020-12-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
