# Generated by Django 3.0.6 on 2020-12-13 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('ref', models.CharField(max_length=250, null=True)),
                ('desc', models.CharField(max_length=250, null=True)),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('buyprice', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('sellpricenormal', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('sellpricesemi_grou', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('sellpricegrou', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('sellspecialprice', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('alert_quantity', models.PositiveIntegerField(default=1)),
                ('box_quantity', models.PositiveIntegerField(default=1)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='types', to='product.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='product.Product')),
            ],
        ),
    ]
