# Generated by Django 3.0.6 on 2020-12-13 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='alert_quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='box_quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sellpricegrou',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sellpricesemi_grou',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sellspecialprice',
        ),
    ]
