# Generated by Django 3.0.6 on 2020-12-15 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyorder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyorder',
            old_name='delivered',
            new_name='factured',
        ),
    ]
